# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . ./

# Expose port for HTTP transport (Dockploy, remote MCP clients)
EXPOSE 8000

# Run with HTTP transport for remote deployment (Dockploy).
# Set TRANSPORT=http and FB_TOKEN via environment variables.
# For local stdio: use "python server.py --fb-token YOUR_TOKEN"
CMD ["python", "server.py"]
